import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
<<<<<<< HEAD
import Footer from "@/components/footer";
=======
>>>>>>> f749a46fd1b7c36ef3d95f28f205de872598b59e

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <Navbar />
        {children}
        <Footer />
=======
        <div>
          <Navbar />
        </div>
        {children}
>>>>>>> f749a46fd1b7c36ef3d95f28f205de872598b59e
      </body>
    </html>
  );
}
